# Generated by Django 2.1.1 on 2018-09-05 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dependency',
            },
        ),
        migrations.CreateModel(
            name='ModeratorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderator',
            },
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('worker', 'Worker'), ('system', 'System'), ('storage', 'Storage'), ('queue', 'Queue'), ('database', 'Database'), ('web', 'Web'), ('client/web', 'Web Client'), ('client/desktop', 'Desktop Client'), ('client/mobile', 'Mobile Client')], max_length=255)),
                ('repo_info', models.TextField(default='')),
                ('environment_config', models.TextField(default='')),
                ('staging_info', models.TextField(default='')),
                ('production_info', models.TextField(default='')),
                ('api_info', models.TextField(default='')),
                ('documentation', models.TextField(default='')),
                ('deployment_type', models.CharField(choices=[('shared', 'Shared Hosting'), ('dedicated', 'Dedicated Server'), ('vm', 'Virtual Machine'), ('container', 'Container')], max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_systems', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(related_name='system_dependencies', through='system.DependencyModel', to='system.SystemModel')),
                ('moderators', models.ManyToManyField(related_name='moderators', through='system.ModeratorModel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system',
            },
        ),
        migrations.AddField(
            model_name='moderatormodel',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.SystemModel'),
        ),
        migrations.AddField(
            model_name='dependencymodel',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.SystemModel'),
        ),
        migrations.AddField(
            model_name='dependencymodel',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.SystemModel'),
        ),
    ]
