# Generated by Django 2.1.1 on 2018-09-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='deployment_type',
            field=models.CharField(choices=[('shared', 'Shared Hosting'), ('dedicated', 'Dedicated Server'), ('vm', 'Virtual Machine'), ('container', 'Container'), ('service', 'Service')], max_length=255),
        ),
        migrations.AddField(
            model_name='systemmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_systems', to='system.ProjectModel'),
        ),
    ]
