# Generated by Django 2.1.1 on 2018-09-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180905_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencymodel',
            old_name='consumer',
            new_name='depends_on',
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='api_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='documentation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='environment_config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='production_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='repo_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='systemmodel',
            name='staging_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
