# Generated by Django 2.1.1 on 2018-09-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180906_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message_template', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='ProjectAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.AppModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_apps', to='system.ProjectModel')),
            ],
            options={
                'db_table': 'project_app',
            },
        ),
        migrations.CreateModel(
            name='SystemAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.AppModel')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_apps', to='system.SystemModel')),
            ],
            options={
                'db_table': 'system_app',
            },
        ),
    ]
