# Generated by Django 2.1.1 on 2018-09-07 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0004_appmodel_projectappmodel_systemappmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDependencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'system_dependency',
            },
        ),
        migrations.CreateModel(
            name='SystemModeratorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_moderator',
            },
        ),
        migrations.RemoveField(
            model_name='dependencymodel',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='dependencymodel',
            name='system',
        ),
        migrations.RemoveField(
            model_name='moderatormodel',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='moderatormodel',
            name='system',
        ),
        migrations.RemoveField(
            model_name='systemmodel',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='systemmodel',
            name='moderators',
        ),
        migrations.DeleteModel(
            name='DependencyModel',
        ),
        migrations.DeleteModel(
            name='ModeratorModel',
        ),
        migrations.AddField(
            model_name='systemmoderatormodel',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='system.SystemModel'),
        ),
        migrations.AddField(
            model_name='systemdependencymodel',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.SystemModel'),
        ),
        migrations.AddField(
            model_name='systemdependencymodel',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='system.SystemModel'),
        ),
    ]
