# Generated by Django 2.1.1 on 2018-09-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20180907_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
