# Generated by Django 2.1.1 on 2018-09-10 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0006_auto_20180908_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectappmodel',
            unique_together={('project', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='systemappmodel',
            unique_together={('system', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='systemdependencymodel',
            unique_together={('system', 'depends_on')},
        ),
        migrations.AlterUniqueTogether(
            name='systemmoderatormodel',
            unique_together={('system', 'moderator')},
        ),
    ]
