# Generated by Django 2.1.1 on 2018-09-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20180910_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAppPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('project_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_app_posts', to='system.SystemAppModel')),
            ],
            options={
                'db_table': 'project_app_post',
            },
        ),
        migrations.CreateModel(
            name='SystemAppPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('system_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_app_posts', to='system.SystemAppModel')),
            ],
            options={
                'db_table': 'system_app_post',
            },
        ),
    ]
