# Generated by Django 2.1.1 on 2018-09-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_projectapppostmodel_systemapppostmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectapppostmodel',
            table='project_app_post',
        ),
    ]
