# Generated by Django 2.1.1 on 2018-09-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20180910_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapppostmodel',
            name='project_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_app_posts', to='system.ProjectAppModel'),
        ),
    ]
