# Generated by Django 2.1.1 on 2018-09-12 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0010_auto_20180910_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_access',
            },
        ),
        migrations.CreateModel(
            name='SystemAccessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'system_access',
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemaccessmodel',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.SystemModel'),
        ),
        migrations.AddField(
            model_name='systemaccessmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectaccessmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='system.ProjectModel'),
        ),
        migrations.AddField(
            model_name='projectaccessmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
