# Generated by Django 2.1.1 on 2018-09-12 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0011_auto_20180912_0421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemmoderatormodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='systemmoderatormodel',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='systemmoderatormodel',
            name='system',
        ),
        migrations.AlterUniqueTogether(
            name='projectaccessmodel',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='systemaccessmodel',
            unique_together={('system', 'user')},
        ),
        migrations.DeleteModel(
            name='SystemModeratorModel',
        ),
    ]
